### ISSUE TITLE
GLES20Canvas.drawRoundRect NullPointerException

### ISSUE THREAD

**Issue by githubfan12221030** [woozzu/IndexableListView#16]
Hello.
Thanks for your excellent library.
But when i am going to implement this to my Listview, i am getting nullpointerexception.
java.lang.NullPointerException
            at android.view.GLES20Canvas.drawRoundRect(GLES20Canvas.java:1222)
            at com.hagoole.handofgod.widget.IndexScroller.draw(IndexScroller.java:75)
            at com.hagoole.handofgod.widget.IndexableListView.draw(IndexableListView.java:70)
            at android.view.View.getDisplayList(View.java:13448)
            at android.view.View.getDisplayList(View.java:13490)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3088)
            at android.view.View.getDisplayList(View.java:13386)
            at android.view.View.getDisplayList(View.java:13490)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3088)
            at android.view.View.getDisplayList(View.java:13386)
            at android.view.View.getDisplayList(View.java:13490)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3088)
            at android.view.View.getDisplayList(View.java:13386)
            at android.view.View.getDisplayList(View.java:13490)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3088)
            at android.view.View.getDisplayList(View.java:13386)
            at android.view.View.getDisplayList(View.java:13490)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3088)
            at android.view.View.getDisplayList(View.java:13386)
            at android.view.View.getDisplayList(View.java:13490)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3088)
            at android.view.View.getDisplayList(View.java:13386)
            at android.view.View.getDisplayList(View.java:13490)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3088)
            at android.view.View.getDisplayList(View.java:13386)
            at android.view.View.getDisplayList(View.java:13490)
            at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2415)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2287)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1910)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1013)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5736)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:544)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5068)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
            at dalvik.system.NativeStart.main(Native Method)

Anyone help me. 
Thanks.

**Comment by PalakSDarji** [comment]
I am getting same error ... What are the solutions? What have you done? please guide me.

**Comment by stefanos-** [comment]
I'm getting same error too.. Any solution?
